apiVersion: apps/v1
kind: Deployment
metadata:
  name: fa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fa-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fa-app
    spec:
      containers:
      - image: quay.io/mjhall77/rhoai-fa-app:v1
        imagePullPolicy: IfNotPresent
        name: container
        ports:
        - containerPort: 8051
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler

---
apiVersion: v1
kind: Service
metadata:
  name: fa-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8501
  selector:
    app: fa-app

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fa-app
spec:
  port:
    targetPort: 8501
  to:
    kind: Service
    name: fa-app
    weight: 100
  wildcardPolicy: None
