---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: facial-aging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fa-app
  namespace: facial-aging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fa-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fa-app
    spec:
      containers:
      - image: quay.io/mjhall77/rhoai-fa-app:v1
        imagePullPolicy: IfNotPresent
        name: container
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fa-app-sa
      ServiceAccountName: fa-app-sa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fa-app-sa
  namespace: facial-aging

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anyuid-for-fa-app-sa-serviceaccount-binding
  namespace: facial-aging
subjects:
- kind: ServiceAccount
  name: fa-app-sa
  namespace: facial-aging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid

---
apiVersion: v1
kind: Service
metadata:
  name: fa-app
  namespace: facial-aging
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8501
  selector:
    app: fa-app

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fa-app
  namespace: facial-aging
spec:
  port:
    targetPort: 8501
  to:
    kind: Service
    name: fa-app
    weight: 100
  wildcardPolicy: None
